/** IBM WRLD — verified offices, subsidiaries, strategic partners, clients, quantum hubs */

const SITE_TYPES = {
    office: {
        label: "Office",
        color: "#0f62fe",
        markerCore: "#4da3ff",
        markerGlow: "rgba(77, 163, 255, 0.65)",
        abbr: "O",
    },
    client: {
        label: "Client",
        color: "#ee5396",
        markerCore: "#ff6eb4",
        markerGlow: "rgba(255, 110, 180, 0.6)",
        abbr: "C",
    },
    partner: {
        label: "Dependency",
        color: "#ff832b",
        markerCore: "#ffab4d",
        markerGlow: "rgba(255, 171, 77, 0.6)",
        abbr: "D",
    },
    initiative: {
        label: "Initiative",
        color: "#8a3ffc",
        markerCore: "#b47aff",
        markerGlow: "rgba(180, 122, 255, 0.65)",
        abbr: "I",
    },
};

const IBM_SITES = [
    { lon: -73.7246, lat: 41.1084, type: "office", name: "Armonk Headquarters", city: "Armonk, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -97.7202, lat: 30.4042, type: "office", name: "IBM Austin", city: "Austin, Texas, United States", region: "Americas", source: "IBM Locations" },
    { lon: -121.8041, lat: 37.2081, type: "office", name: "IBM Silicon Valley Lab", city: "San Jose, California, United States", region: "Americas", source: "IBM Silicon Valley" },
    { lon: -78.8559, lat: 35.9132, type: "office", name: "IBM Research Triangle Park", city: "Durham, North Carolina, United States", region: "Americas", source: "IBM Locations" },
    { lon: -71.0825, lat: 42.3628, type: "office", name: "IBM Cambridge", city: "Cambridge, Massachusetts, United States", region: "Americas", source: "IBM Research" },
    { lon: -73.9317, lat: 41.6501, type: "office", name: "IBM Poughkeepsie", city: "Poughkeepsie, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -96.797, lat: 32.7767, type: "office", name: "IBM Dallas", city: "Dallas, Texas, United States", region: "Americas", source: "IBM Cloud" },
    { lon: -87.6219, lat: 41.8885, type: "office", name: "IBM Chicago", city: "Chicago, Illinois, United States", region: "Americas", source: "IBM Locations" },
    { lon: -84.4578, lat: 33.8961, type: "office", name: "IBM Atlanta", city: "Atlanta, Georgia, United States", region: "Americas", source: "IBM Locations" },
    { lon: -79.3341, lat: 43.8471, type: "office", name: "IBM Toronto Software Lab", city: "Markham, Ontario, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -73.5693, lat: 45.4984, type: "office", name: "IBM Montreal", city: "Montreal, Quebec, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -99.2559, lat: 19.3663, type: "office", name: "IBM Mexico", city: "Mexico City, CDMX, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -103.2678, lat: 20.5372, type: "office", name: "IBM Guadalajara", city: "El Salto, Jalisco, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -46.6433, lat: -23.5855, type: "office", name: "IBM São Paulo", city: "São Paulo, São Paulo, Brazil", region: "Americas", source: "IBM Brazil" },
    { lon: -58.3739, lat: -34.5937, type: "office", name: "IBM Argentina", city: "Buenos Aires, CABA, Argentina", region: "Americas", source: "IBM Argentina" },
    { lon: -74.0436, lat: 4.6853, type: "office", name: "IBM Colombia", city: "Bogotá, Bogotá, Colombia", region: "Americas", source: "IBM Colombia" },
    { lon: -0.1147, lat: 51.5036, type: "office", name: "IBM London", city: "London, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -1.3965, lat: 51.0264, type: "office", name: "IBM Hursley", city: "Winchester, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -6.4172, lat: 53.4116, type: "office", name: "IBM Dublin", city: "Dublin, County Dublin, Ireland", region: "EMEA", source: "IBM Ireland" },
    { lon: 2.2688, lat: 48.9189, type: "office", name: "IBM France HQ", city: "Bois-Colombes, Île-de-France, France", region: "EMEA", source: "IBM France" },
    { lon: -3.6685, lat: 40.4507, type: "office", name: "IBM Spain", city: "Madrid, Madrid, Spain", region: "EMEA", source: "IBM Spain" },
    { lon: 12.4332, lat: 41.8152, type: "office", name: "IBM Italy", city: "Rome, Lazio, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 9.3005, lat: 45.4808, type: "office", name: "IBM Milan", city: "Segrate, Lombardy, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 8.5521, lat: 47.3092, type: "office", name: "IBM Research Zurich", city: "Rüschlikon, Zurich, Switzerland", region: "EMEA", source: "IBM Research" },
    { lon: 8.9792, lat: 48.6756, type: "office", name: "IBM Germany R&D", city: "Böblingen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 11.5925, lat: 48.1755, type: "office", name: "IBM Munich", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 8.5721, lat: 50.1346, type: "office", name: "IBM Frankfurt", city: "Frankfurt, Hesse, Germany", region: "EMEA", source: "IBM Cloud" },
    { lon: 4.8276, lat: 52.3421, type: "office", name: "IBM Netherlands", city: "Amsterdam, North Holland, Netherlands", region: "EMEA", source: "IBM Netherlands" },
    { lon: 14.3971, lat: 50.1504, type: "office", name: "IBM Czech Republic", city: "Prague, Prague, Czechia", region: "EMEA", source: "IBM CZ" },
    { lon: 19.8974, lat: 50.0827, type: "office", name: "IBM Poland", city: "Kraków, Lesser Poland, Poland", region: "EMEA", source: "IBM Poland" },
    { lon: 34.8085, lat: 32.0699, type: "office", name: "IBM Israel", city: "Givatayim, Tel Aviv, Israel", region: "EMEA", source: "IBM Israel" },
    { lon: 55.1633, lat: 25.0994, type: "office", name: "IBM UAE", city: "Dubai, Dubai, UAE", region: "EMEA", source: "IBM Middle East" },
    { lon: 28.0494, lat: -26.1035, type: "office", name: "IBM South Africa", city: "Sandton, Gauteng, South Africa", region: "EMEA", source: "IBM South Africa" },
    { lon: 77.5946, lat: 12.9716, type: "office", name: "IBM Bangalore", city: "Bangalore, Karnataka, India", region: "APAC", source: "IBM India" },
    { lon: 73.9806, lat: 18.5793, type: "office", name: "IBM Pune", city: "Pune, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 78.3756, lat: 17.4474, type: "office", name: "IBM Hyderabad", city: "Hyderabad, Telangana, India", region: "APAC", source: "IBM India" },
    { lon: 80.2281, lat: 12.8953, type: "office", name: "IBM Chennai", city: "Chennai, Tamil Nadu, India", region: "APAC", source: "IBM India" },
    { lon: 72.8596, lat: 19.1025, type: "office", name: "IBM Mumbai", city: "Mumbai, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 139.7871, lat: 35.6791, type: "office", name: "IBM Japan HQ", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 135.5023, lat: 34.6937, type: "office", name: "IBM Osaka", city: "Osaka, Osaka, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 116.2796, lat: 40.0464, type: "office", name: "IBM Research China", city: "Beijing, Beijing, China", region: "APAC", source: "IBM China" },
    { lon: 121.3994, lat: 31.2117, type: "office", name: "IBM Shanghai", city: "Shanghai, Shanghai, China", region: "APAC", source: "IBM China" },
    { lon: 126.9247, lat: 37.5256, type: "office", name: "IBM Korea", city: "Seoul, Seoul, South Korea", region: "APAC", source: "IBM Korea" },
    { lon: 121.5645, lat: 25.0345, type: "office", name: "IBM Taiwan", city: "Taipei, Taipei, Taiwan", region: "APAC", source: "IBM Taiwan" },
    { lon: 103.9632, lat: 1.3341, type: "office", name: "IBM Singapore", city: "Singapore, Singapore, Singapore", region: "APAC", source: "IBM Singapore" },
    { lon: 101.6146, lat: 3.1368, type: "office", name: "IBM Malaysia", city: "Kuala Lumpur, Federal Territory, Malaysia", region: "APAC", source: "IBM Malaysia" },
    { lon: 121.0543, lat: 14.6214, type: "office", name: "IBM Philippines", city: "Quezon City, Metro Manila, Philippines", region: "APAC", source: "IBM Philippines" },
    { lon: 151.1963, lat: -33.8214, type: "office", name: "IBM Sydney", city: "St Leonards, New South Wales, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 144.9626, lat: -37.8229, type: "office", name: "IBM Melbourne", city: "Southbank, Victoria, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 174.7633, lat: -36.8485, type: "office", name: "IBM New Zealand", city: "Auckland, Auckland, New Zealand", region: "APAC", source: "IBM New Zealand" },
    { id: "ibm-kochi-wtc", lon: 76.363, lat: 10.015, type: "office", name: "IBM Kochi WTC", city: "Kochi, Kerala, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-noida", lon: 77.4055, lat: 28.5042, type: "office", name: "IBM Noida", city: "Noida, Uttar Pradesh, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-hong-kong", lon: 114.1717, lat: 22.2796, type: "office", name: "IBM Hong Kong", city: "Hong Kong, Hong Kong, China", region: "APAC", source: "IBM HK" },
    { id: "ibm-jakarta", lon: 106.8043, lat: -6.2238, type: "office", name: "IBM Indonesia", city: "Jakarta, Jakarta, Indonesia", region: "APAC", source: "IBM Indonesia" },
    { id: "ibm-bangkok", lon: 100.5428, lat: 13.7801, type: "office", name: "IBM Thailand", city: "Bangkok, Bangkok, Thailand", region: "APAC", source: "IBM Thailand" },
    { id: "ibm-brisbane", lon: 153.0251, lat: -27.4698, type: "office", name: "IBM Brisbane", city: "Brisbane, Queensland, Australia", region: "APAC", source: "IBM Australia" },
    { id: "ibm-wellington", lon: 174.7797, lat: -41.2822, type: "office", name: "IBM Wellington", city: "Wellington, Wellington, New Zealand", region: "APAC", source: "IBM NZ" },
    { id: "ibm-ehningen-hq", lon: 8.9416, lat: 48.6575, type: "office", name: "IBM Germany HQ", city: "Ehningen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Germany", subtype: "hq" },
    { id: "ibm-montpellier", lon: 3.8741, lat: 43.6146, type: "office", name: "IBM Montpellier", city: "Montpellier, Occitanie, France", region: "EMEA", source: "IBM France", subtype: "client_center" },
    { id: "ibm-brno", lon: 16.596, lat: 49.214, type: "office", name: "IBM Brno", city: "Brno, South Moravian, Czechia", region: "EMEA", source: "IBM CZ", subtype: "delivery_center" },
    { id: "ibm-budapest", lon: 19.0594, lat: 47.4734, type: "office", name: "IBM Hungary", city: "Budapest, Budapest, Hungary", region: "EMEA", source: "IBM Hungary", subtype: "delivery_center" },
    { id: "ibm-warsaw", lon: 20.9859, lat: 52.2309, type: "office", name: "IBM Poland HQ", city: "Warsaw, Masovian, Poland", region: "EMEA", source: "IBM Poland", subtype: "hq" },
    { id: "ibm-bucharest", lon: 26.103, lat: 44.4429, type: "office", name: "IBM Romania", city: "Bucharest, Bucharest, Romania", region: "EMEA", source: "IBM Romania", subtype: "delivery_center" },
    { id: "ibm-stockholm", lon: 17.9547, lat: 59.4045, type: "office", name: "IBM Sweden", city: "Stockholm, Stockholm, Sweden", region: "EMEA", source: "IBM Sweden", subtype: "hq" },
    { id: "ibm-copenhagen", lon: 12.5768, lat: 55.6375, type: "office", name: "IBM Denmark", city: "Copenhagen, Capital Region, Denmark", region: "EMEA", source: "IBM Denmark", subtype: "hq" },
    { id: "ibm-riyadh", lon: 46.702, lat: 24.7296, type: "office", name: "IBM Saudi Arabia", city: "Riyadh, Riyadh, Saudi Arabia", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-cairo", lon: 31.2089, lat: 30.0131, type: "office", name: "IBM Egypt", city: "Cairo, Cairo, Egypt", region: "EMEA", source: "IBM Egypt", subtype: "delivery_center" },
    { id: "ibm-casablanca", lon: -7.6038, lat: 33.5898, type: "office", name: "IBM Morocco", city: "Casablanca, Casablanca-Settat, Morocco", region: "EMEA", source: "IBM Morocco" },
    { id: "ibm-nyc-astor", lon: -73.9904, lat: 40.7303, type: "office", name: "IBM New York City", city: "New York, New York, United States", region: "Americas", source: "IBM Locations", subtype: "client_center" },
    { id: "ibm-rochester", lon: -92.5029, lat: 44.0535, type: "office", name: "IBM Rochester", city: "Rochester, Minnesota, United States", region: "Americas", source: "IBM Locations", subtype: "lab" },
    { id: "ibm-washington-dc", lon: -77.0315, lat: 38.9011, type: "office", name: "IBM Washington DC", city: "Washington, DC, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-ottawa", lon: -75.7483, lat: 45.34, type: "office", name: "IBM Ottawa", city: "Ottawa, Ontario, Canada", region: "Americas", source: "IBM Canada" },
    { id: "ibm-hortolandia", lon: -47.2023, lat: -22.8687, type: "office", name: "IBM Hortolândia", city: "Hortolândia, São Paulo, Brazil", region: "Americas", source: "IBM Brazil", subtype: "delivery_center" },
    { id: "ibm-santiago", lon: -70.6133, lat: -33.4243, type: "office", name: "IBM Chile", city: "Santiago, Santiago Metropolitan, Chile", region: "Americas", source: "IBM Chile" },
    { id: "ibm-costa-rica", lon: -84.1198, lat: 9.998, type: "office", name: "IBM Costa Rica", city: "Heredia, Heredia, Costa Rica", region: "Americas", source: "IBM Costa Rica", subtype: "delivery_center" },
    { id: "ibm-lima", lon: -77.0252, lat: -12.0963, type: "office", name: "IBM Peru", city: "Lima, Lima, Peru", region: "Americas", source: "IBM Peru" },
    { id: "ibm-yorktown-research", lon: -73.8016, lat: 41.2104, type: "office", name: "IBM Thomas J. Watson Research Center", city: "Yorktown Heights, New York, United States", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-almaden-research", lon: -121.808, lat: 37.2105, type: "office", name: "IBM Research Almaden", city: "San Jose, California, United States", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-boulder", lon: -105.2014, lat: 40.0632, type: "office", name: "IBM Boulder", city: "Boulder, Colorado, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-bromont", lon: -72.6713, lat: 45.3025, type: "office", name: "IBM Bromont", city: "Bromont, Quebec, Canada", region: "Americas", source: "IBM Canada", subtype: "manufacturing" },
    { id: "ibm-rio-research", lon: -43.175, lat: -22.9519, type: "office", name: "IBM Research Brazil", city: "Rio de Janeiro, Rio de Janeiro, Brazil", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-nairobi-research", lon: 36.7578, lat: -1.2581, type: "office", name: "IBM Research Africa", city: "Nairobi, Nairobi, Kenya", region: "EMEA", source: "IBM Research", subtype: "research" },
    { id: "ibm-haifa-research", lon: 34.995, lat: 32.7601, type: "office", name: "IBM Research Haifa", city: "Haifa, Haifa, Israel", region: "EMEA", source: "IBM Research", subtype: "research" },
    { id: "ibm-vienna", lon: 16.3773, lat: 48.2255, type: "office", name: "IBM Austria", city: "Vienna, Vienna, Austria", region: "EMEA", source: "IBM Austria" },
    { id: "ibm-brussels", lon: 4.3644, lat: 50.8548, type: "office", name: "IBM Belgium", city: "Brussels, Brussels, Belgium", region: "EMEA", source: "IBM Belgium" },
    { id: "ibm-helsinki", lon: 24.8778, lat: 60.2227, type: "office", name: "IBM Finland", city: "Helsinki, Uusimaa, Finland", region: "EMEA", source: "IBM Finland" },
    { id: "ibm-oslo", lon: 10.7605, lat: 59.9142, type: "office", name: "IBM Norway", city: "Oslo, Oslo, Norway", region: "EMEA", source: "IBM Norway" },
    { id: "ibm-lisbon", lon: -9.1388, lat: 38.7369, type: "office", name: "IBM Portugal", city: "Lisbon, Lisbon, Portugal", region: "EMEA", source: "IBM Portugal" },
    { id: "ibm-athens", lon: 23.8055, lat: 38.0264, type: "office", name: "IBM Greece", city: "Athens, Attica, Greece", region: "EMEA", source: "IBM Greece" },
    { id: "ibm-istanbul", lon: 29.0145, lat: 41.0847, type: "office", name: "IBM Turkey", city: "Istanbul, Istanbul, Turkey", region: "EMEA", source: "IBM Turkey" },
    { id: "ibm-cyberjaya", lon: 101.6569, lat: 2.9221, type: "office", name: "IBM Cyberjaya", city: "Cyberjaya, Selangor, Malaysia", region: "APAC", source: "IBM Malaysia", subtype: "delivery_center" },
    { id: "ibm-ho-chi-minh", lon: 106.7009, lat: 10.7769, type: "office", name: "IBM Vietnam", city: "Ho Chi Minh City, HCMC, Vietnam", region: "APAC", source: "IBM Vietnam" },
    { id: "ibm-perth", lon: 115.8605, lat: -31.9505, type: "office", name: "IBM Perth", city: "Perth, Western Australia, Australia", region: "APAC", source: "IBM Australia" },
    { id: "ibm-colombo", lon: 79.8612, lat: 6.9271, type: "office", name: "IBM Sri Lanka", city: "Colombo, Western Province, Sri Lanka", region: "APAC", source: "IBM Sri Lanka" },
    { id: "ibm-coimbatore", lon: 76.9558, lat: 11.0168, type: "office", name: "IBM Coimbatore", city: "Coimbatore, Tamil Nadu, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-gurugram", lon: 77.0266, lat: 28.4595, type: "office", name: "IBM Gurugram", city: "Gurugram, Haryana, India", region: "APAC", source: "IBM India" },
    { id: "ibm-kolkata", lon: 88.4716, lat: 22.5867, type: "office", name: "IBM Kolkata", city: "Kolkata, West Bengal, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-bhubaneswar", lon: 85.8245, lat: 20.2961, type: "office", name: "IBM Bhubaneswar", city: "Bhubaneswar, Odisha, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-yamato-lab", lon: 139.4124, lat: 35.6186, type: "office", name: "IBM Yamato Facility", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Japan", subtype: "lab" },
    { id: "ibm-nagoya", lon: 136.9066, lat: 35.1814, type: "office", name: "IBM Nagoya", city: "Nagoya, Aichi, Japan", region: "APAC", source: "IBM Japan" },
    { id: "ibm-manila-eastwood", lon: 121.0801, lat: 14.6092, type: "office", name: "IBM Manila Eastwood", city: "Quezon City, Metro Manila, Philippines", region: "APAC", source: "IBM Philippines", subtype: "delivery_center" },
    { id: "ibm-bratislava", lon: 17.1077, lat: 48.1486, type: "office", name: "IBM Bratislava", city: "Bratislava, Bratislava Region, Slovakia", region: "EMEA", source: "IBM Slovakia", subtype: "delivery_center" },
    { id: "ibm-barcelona", lon: 2.1734, lat: 41.3851, type: "office", name: "IBM Barcelona", city: "Barcelona, Catalonia, Spain", region: "EMEA", source: "IBM Spain", subtype: "client_center" },
    { id: "ibm-lyon", lon: 4.8357, lat: 45.764, type: "office", name: "IBM Lyon", city: "Lyon, Auvergne-Rhône-Alpes, France", region: "EMEA", source: "IBM France" },
    { id: "ibm-sofia", lon: 23.3219, lat: 42.6977, type: "office", name: "IBM Bulgaria", city: "Sofia, Sofia City, Bulgaria", region: "EMEA", source: "IBM Bulgaria", subtype: "delivery_center" },
    { id: "ibm-abu-dhabi", lon: 54.3773, lat: 24.4539, type: "office", name: "IBM Abu Dhabi", city: "Abu Dhabi, Abu Dhabi, UAE", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-doha", lon: 51.531, lat: 25.2854, type: "office", name: "IBM Qatar", city: "Doha, Doha, Qatar", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-lagos", lon: 3.4219, lat: 6.4281, type: "office", name: "IBM Nigeria", city: "Lagos, Lagos State, Nigeria", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-calgary", lon: -114.0719, lat: 51.0447, type: "office", name: "IBM Calgary", city: "Calgary, Alberta, Canada", region: "Americas", source: "IBM Canada", subtype: "client_center" },
    { id: "ibm-monterrey", lon: -100.3161, lat: 25.6866, type: "office", name: "IBM Monterrey", city: "Monterrey, Nuevo León, Mexico", region: "Americas", source: "IBM Mexico" },
    { id: "ibm-brasilia", lon: -47.8822, lat: -15.7942, type: "office", name: "IBM Brasília", city: "Brasília, Federal District, Brazil", region: "Americas", source: "IBM Brazil" },
    { id: "ibm-medellin", lon: -75.5812, lat: 6.2442, type: "office", name: "IBM Medellín", city: "Medellín, Antioquia, Colombia", region: "Americas", source: "IBM Colombia", subtype: "delivery_center" },
    { id: "ibm-warwick", lon: -1.5842, lat: 52.2801, type: "office", name: "IBM Warwick", city: "Warwick, Warwickshire, United Kingdom", region: "EMEA", source: "IBM UK", subtype: "campus" },
    { id: "ibm-littleton", lon: -71.4801, lat: 42.5401, type: "office", name: "IBM Littleton Lab", city: "Littleton, Massachusetts, United States", region: "Americas", source: "IBM Locations", subtype: "lab" },
    { id: "ibm-groningen", lon: 6.5665, lat: 53.2194, type: "office", name: "IBM Groningen CIC", city: "Groningen, Groningen, Netherlands", region: "EMEA", source: "IBM Netherlands", subtype: "client_center" },
    { id: "ibm-wroclaw", lon: 17.0385, lat: 51.1079, type: "office", name: "IBM Wrocław", city: "Wrocław, Lower Silesian, Poland", region: "EMEA", source: "IBM Poland", subtype: "delivery_center" },
    { id: "ibm-katowice", lon: 19.0238, lat: 50.2649, type: "office", name: "IBM Katowice", city: "Katowice, Silesian, Poland", region: "EMEA", source: "IBM Poland", subtype: "delivery_center" },
    { id: "ibm-berlin", lon: 13.405, lat: 52.52, type: "office", name: "IBM Berlin", city: "Berlin, Berlin, Germany", region: "EMEA", source: "IBM Germany" },
    { id: "ibm-hamburg", lon: 9.9937, lat: 53.5511, type: "office", name: "IBM Hamburg", city: "Hamburg, Hamburg, Germany", region: "EMEA", source: "IBM Germany" },
    { id: "ibm-mysuru", lon: 76.6394, lat: 12.2958, type: "office", name: "IBM Mysuru", city: "Mysuru, Karnataka, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-gandhinagar", lon: 72.6369, lat: 23.2156, type: "office", name: "IBM Gandhinagar", city: "Gandhinagar, Gujarat, India", region: "APAC", source: "IBM India" },
    { id: "ibm-ashburn", lon: -77.4875, lat: 39.0438, type: "office", name: "IBM Ashburn Data Center", city: "Ashburn, Virginia, United States", region: "Americas", source: "IBM Cloud", subtype: "cloud_region" },
    { id: "ibm-northcastle", lon: -73.712, lat: 41.114, type: "office", name: "IBM North Castle", city: "Armonk, New York, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-queretaro", lon: -100.3899, lat: 20.5888, type: "office", name: "IBM Querétaro", city: "Querétaro, Querétaro, Mexico", region: "Americas", source: "IBM Cloud", subtype: "cloud_region" },
    { id: "ibm-jeddah", lon: 39.1728, lat: 21.5433, type: "office", name: "IBM Jeddah", city: "Jeddah, Makkah, Saudi Arabia", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-capetown", lon: 18.4241, lat: -33.9249, type: "office", name: "IBM Cape Town", city: "Cape Town, Western Cape, South Africa", region: "EMEA", source: "IBM South Africa" },
    { id: "ibm-accra", lon: -0.187, lat: 5.6037, type: "office", name: "IBM Ghana", city: "Accra, Greater Accra, Ghana", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-halifax", lon: -63.5752, lat: 44.6488, type: "office", name: "IBM Halifax CIC", city: "Halifax, Nova Scotia, Canada", region: "Americas", source: "IBM Canada", subtype: "delivery_center" },
    { id: "ibm-baton-rouge", lon: -91.1871, lat: 30.4515, type: "office", name: "IBM Baton Rouge CIC", city: "Baton Rouge, Louisiana, United States", region: "Americas", source: "IBM Locations", subtype: "delivery_center" },
    { id: "ibm-monroe-la", lon: -92.1193, lat: 32.5093, type: "office", name: "IBM Monroe CIC", city: "Monroe, Louisiana, United States", region: "Americas", source: "IBM Locations", subtype: "delivery_center" },
    { id: "ibm-lansing", lon: -84.5555, lat: 42.7325, type: "office", name: "IBM Lansing CIC", city: "East Lansing, Michigan, United States", region: "Americas", source: "IBM Locations", subtype: "delivery_center" },
    { id: "ibm-buffalo", lon: -78.8787, lat: 42.8802, type: "office", name: "IBM Buffalo", city: "Buffalo, New York, United States", region: "Americas", source: "IBM Locations", subtype: "client_center" },
    { id: "ibm-san-francisco", lon: -122.396, lat: 37.7891, type: "office", name: "IBM San Francisco", city: "San Francisco, California, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-campinas", lon: -47.0626, lat: -22.9099, type: "office", name: "IBM Campinas", city: "Campinas, São Paulo, Brazil", region: "Americas", source: "IBM Brazil", subtype: "delivery_center" },
    { id: "ibm-montevideo", lon: -56.1645, lat: -34.9011, type: "office", name: "IBM Uruguay", city: "Montevideo, Montevideo, Uruguay", region: "Americas", source: "IBM Uruguay" },
    { id: "ibm-ostrava", lon: 18.2625, lat: 49.8209, type: "office", name: "IBM Ostrava", city: "Ostrava, Moravian-Silesian, Czechia", region: "EMEA", source: "IBM CZ", subtype: "delivery_center" },
    { id: "ibm-kosice", lon: 21.2611, lat: 48.7164, type: "office", name: "IBM Košice", city: "Košice, Košice Region, Slovakia", region: "EMEA", source: "IBM Slovakia", subtype: "delivery_center" },
    { id: "ibm-szekesfehervar", lon: 18.4103, lat: 47.1899, type: "office", name: "IBM Székesfehérvár", city: "Székesfehérvár, Fejér, Hungary", region: "EMEA", source: "IBM Hungary", subtype: "delivery_center" },
    { id: "ibm-leicester", lon: -1.1398, lat: 52.6369, type: "office", name: "IBM Leicester CIC", city: "Leicester, England, United Kingdom", region: "EMEA", source: "IBM UK", subtype: "delivery_center" },
    { id: "ibm-turin", lon: 7.6869, lat: 45.0703, type: "office", name: "IBM Turin", city: "Turin, Piedmont, Italy", region: "EMEA", source: "IBM Italy" },
    { id: "ibm-dakar", lon: -17.4677, lat: 14.7167, type: "office", name: "IBM Senegal", city: "Dakar, Dakar, Senegal", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-kuwait-city", lon: 47.9774, lat: 29.3759, type: "office", name: "IBM Kuwait", city: "Kuwait City, Al Asimah, Kuwait", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-zagreb", lon: 15.9819, lat: 45.815, type: "office", name: "IBM Croatia", city: "Zagreb, Zagreb, Croatia", region: "EMEA", source: "IBM Croatia" },
    { id: "ibm-dhaka", lon: 90.4125, lat: 23.8103, type: "office", name: "IBM Bangladesh", city: "Dhaka, Dhaka, Bangladesh", region: "APAC", source: "IBM Bangladesh" },
    { id: "ibm-penang", lon: 100.3288, lat: 5.4141, type: "office", name: "IBM Penang", city: "George Town, Penang, Malaysia", region: "APAC", source: "IBM Malaysia", subtype: "delivery_center" },
    { id: "ibm-islamabad", lon: 73.0479, lat: 33.6844, type: "office", name: "IBM Pakistan", city: "Islamabad, Islamabad Capital Territory, Pakistan", region: "APAC", source: "IBM Pakistan" },
    { id: "ibm-charlotte", lon: -80.8431, lat: 35.2271, type: "office", name: "IBM Charlotte", city: "Charlotte, North Carolina, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-quebec-city", lon: -71.208, lat: 46.8139, type: "office", name: "IBM Quebec City", city: "Quebec City, Quebec, Canada", region: "Americas", source: "IBM Canada" },
    { id: "ibm-quito", lon: -78.4678, lat: -0.1807, type: "office", name: "IBM Ecuador", city: "Quito, Pichincha, Ecuador", region: "Americas", source: "IBM Ecuador" },
    { id: "ibm-asuncion", lon: -57.5759, lat: -25.2637, type: "office", name: "IBM Paraguay", city: "Asunción, Asunción, Paraguay", region: "Americas", source: "IBM Paraguay" },
    { id: "ibm-san-juan", lon: -66.0658, lat: 18.4208, type: "office", name: "IBM Puerto Rico", city: "San Juan, Puerto Rico, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-tallinn", lon: 24.7536, lat: 59.437, type: "office", name: "IBM Estonia", city: "Tallinn, Harju County, Estonia", region: "EMEA", source: "IBM Estonia" },
    { id: "ibm-riga", lon: 24.1052, lat: 56.9496, type: "office", name: "IBM Latvia", city: "Riga, Riga, Latvia", region: "EMEA", source: "IBM Latvia" },
    { id: "ibm-vilnius", lon: 25.2797, lat: 54.6872, type: "office", name: "IBM Lithuania", city: "Vilnius, Vilnius County, Lithuania", region: "EMEA", source: "IBM Lithuania" },
    { id: "ibm-ljubljana", lon: 14.5058, lat: 46.0569, type: "office", name: "IBM Slovenia", city: "Ljubljana, Ljubljana, Slovenia", region: "EMEA", source: "IBM Slovenia" },
    { id: "ibm-belgrade", lon: 20.4489, lat: 44.7866, type: "office", name: "IBM Serbia", city: "Belgrade, Belgrade, Serbia", region: "EMEA", source: "IBM Serbia" },
    { id: "ibm-manama", lon: 50.5876, lat: 26.2235, type: "office", name: "IBM Bahrain", city: "Manama, Capital Governorate, Bahrain", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-muscat", lon: 58.4059, lat: 23.5859, type: "office", name: "IBM Oman", city: "Muscat, Muscat, Oman", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-al-khobar", lon: 50.1971, lat: 26.2172, type: "office", name: "IBM Al Khobar", city: "Al Khobar, Eastern Province, Saudi Arabia", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-tunis", lon: 10.1815, lat: 36.8065, type: "office", name: "IBM Tunisia", city: "Tunis, Tunis, Tunisia", region: "EMEA", source: "IBM Tunisia" },
    { id: "ibm-waterloo", lon: -80.5204, lat: 43.4643, type: "office", name: "IBM Waterloo", city: "Waterloo, Ontario, Canada", region: "Americas", source: "IBM Canada", subtype: "lab" },
    { id: "ibm-algiers", lon: 3.0588, lat: 36.7538, type: "office", name: "IBM Algeria", city: "Algiers, Algiers, Algeria", region: "EMEA", source: "IBM Middle East and Africa" },
    { id: "ibm-abidjan", lon: -4.0082, lat: 5.3599, type: "office", name: "IBM Ivory Coast", city: "Abidjan, Abidjan, Ivory Coast", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-luanda", lon: 13.2302, lat: -8.8147, type: "office", name: "IBM Angola", city: "Luanda, Luanda, Angola", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-dar-es-salaam", lon: 39.2083, lat: -6.7924, type: "office", name: "IBM Tanzania", city: "Dar es Salaam, Dar es Salaam, Tanzania", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-kiev", lon: 30.5234, lat: 50.4501, type: "office", name: "IBM Ukraine", city: "Kyiv, Kyiv, Ukraine", region: "EMEA", source: "IBM Ukraine" },
    { id: "ibm-almaty", lon: 76.8512, lat: 43.222, type: "office", name: "IBM Kazakhstan", city: "Almaty, Almaty, Kazakhstan", region: "EMEA", source: "IBM Kazakhstan" },
    { id: "ibm-tashkent", lon: 69.2401, lat: 41.2995, type: "office", name: "IBM Uzbekistan", city: "Tashkent, Tashkent, Uzbekistan", region: "EMEA", source: "IBM Uzbekistan" },
    { id: "ibm-gatineau", lon: -75.2953, lat: 45.4212, type: "office", name: "IBM Gatineau CIC", city: "Gatineau, Quebec, Canada", region: "Americas", source: "IBM Canada", subtype: "delivery_center" },
    { id: "partner-redhat", lon: -78.6375, lat: 35.7754, type: "partner", name: "Red Hat", city: "Raleigh, North Carolina, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-hashicorp", lon: -122.3994, lat: 37.7897, type: "partner", name: "HashiCorp", city: "San Francisco, California, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-microsoft", lon: -122.1215, lat: 47.6740, type: "partner", name: "Microsoft", city: "Redmond, Washington, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-aws", lon: -122.3321, lat: 47.6062, type: "partner", name: "Amazon Web Services", city: "Seattle, Washington, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-sap", lon: 8.6431, lat: 49.2943, type: "partner", name: "SAP", city: "Walldorf, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Partner" },
    { id: "partner-oracle", lon: -97.7431, lat: 30.2672, type: "partner", name: "Oracle", city: "Austin, Texas, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-salesforce", lon: -122.3964, lat: 37.7898, type: "partner", name: "Salesforce", city: "San Francisco, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-adobe", lon: -121.8942, lat: 37.3305, type: "partner", name: "Adobe", city: "San Jose, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-paloalto", lon: -121.9680, lat: 37.4043, type: "partner", name: "Palo Alto Networks", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-confluent", lon: -122.0819, lat: 37.3897, type: "partner", name: "Confluent", city: "Mountain View, California, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-intel", lon: -121.9637, lat: 37.3875, type: "partner", name: "Intel", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Semiconductor" },
    { id: "partner-samsung", lon: 127.0286, lat: 37.2636, type: "partner", name: "Samsung Electronics", city: "Suwon, Gyeonggi, South Korea", region: "APAC", source: "IBM Foundry" },
    { id: "partner-lam-research", lon: -121.9415, lat: 37.4882, type: "partner", name: "Lam Research", city: "Fremont, California, United States", region: "Americas", source: "IBM Semiconductor" },
    { id: "partner-tokyo-electron", lon: 139.7310, lat: 35.6694, type: "partner", name: "Tokyo Electron", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Semiconductor" },
    { id: "partner-globalfoundries", lon: -73.7847, lat: 43.0380, type: "partner", name: "GlobalFoundries", city: "Malta, New York, United States", region: "Americas", source: "IBM Foundry" },
    { id: "partner-google-cloud", lon: -122.0840, lat: 37.4220, type: "partner", name: "Google Cloud", city: "Mountain View, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-snowflake", lon: -122.2280, lat: 37.4848, type: "partner", name: "Snowflake", city: "San Mateo, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "client-jpmorgan", lon: -73.9754, lat: 40.7556, type: "client", name: "JPMorgan Chase", city: "New York, New York, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-allianz", lon: 11.5604, lat: 48.1371, type: "client", name: "Allianz", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Case Study" },
    { id: "client-att", lon: -96.8085, lat: 32.7904, type: "client", name: "AT&T", city: "Dallas, Texas, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-hsbc", lon: -0.0850, lat: 51.5130, type: "client", name: "HSBC", city: "London, England, United Kingdom", region: "EMEA", source: "IBM Case Study" },
    { id: "client-elevance-health", lon: -86.1528, lat: 39.7645, type: "client", name: "Elevance Health", city: "Indianapolis, Indiana, United States", region: "Americas", source: "IBM Consulting (watsonx Assistant)" },
    { id: "initiative-anderon", lon: -73.8237, lat: 42.6880, type: "initiative", name: "Anderon Quantum Foundry", city: "Albany, New York, United States", region: "Americas", source: "IBM Spinoff" },
    { id: "initiative-quantum-omaha", lon: -95.9345, lat: 41.2565, type: "initiative", name: "IBM Quantum Network — Omaha", city: "Omaha, Nebraska, United States", region: "Americas", source: "IBM Quantum" },
    { id: "initiative-quantum-munich", lon: 11.5820, lat: 48.1351, type: "initiative", name: "IBM Quantum Network — Munich", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Quantum" },
    { id: "initiative-watsonx", lon: -73.9855, lat: 40.7580, type: "initiative", name: "watsonx.governance — NYC", city: "New York, New York, United States", region: "Americas", source: "IBM Software" },
    { id: "partner-datastax", lon: -121.9746, lat: 37.3839, type: "partner", name: "DataStax", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-apptio", lon: -122.1956, lat: 47.6197, type: "partner", name: "Apptio", city: "Bellevue, Washington, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-turbonomic", lon: -71.2356, lat: 42.3765, type: "partner", name: "Turbonomic", city: "Waltham, Massachusetts, United States", region: "Americas", source: "IBM Subsidiary" },
    { id: "partner-txture", lon: 15.4395, lat: 47.0707, type: "partner", name: "Txture", city: "Graz, Styria, Austria", region: "EMEA", source: "IBM Subsidiary" },
    { id: "partner-servicenow", lon: -121.977, lat: 37.391, type: "partner", name: "ServiceNow", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-nvidia", lon: -121.9665, lat: 37.3709, type: "partner", name: "NVIDIA", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-amd", lon: -121.9724, lat: 37.4852, type: "partner", name: "AMD", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-anthropic", lon: -122.399, lat: 37.7925, type: "partner", name: "Anthropic", city: "San Francisco, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-groq", lon: -122.0516, lat: 37.4063, type: "partner", name: "Groq", city: "Mountain View, California, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-accenture", lon: -87.6229, lat: 41.8857, type: "partner", name: "Accenture", city: "Chicago, Illinois, United States", region: "Americas", source: "IBM Partner" },
    { id: "partner-rapidus", lon: 139.7671, lat: 35.6812, type: "partner", name: "Rapidus", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Semiconductor" },
    { id: "partner-applied-materials", lon: -121.9745, lat: 37.403, type: "partner", name: "Applied Materials", city: "Santa Clara, California, United States", region: "Americas", source: "IBM Semiconductor" },
    { id: "partner-asml", lon: 5.4069, lat: 51.4423, type: "partner", name: "ASML", city: "Veldhoven, North Brabant, Netherlands", region: "EMEA", source: "IBM Semiconductor" },
    { id: "partner-siemens", lon: 11.5755, lat: 48.1372, type: "partner", name: "Siemens", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Semiconductor" },
    { id: "partner-imec", lon: 4.6938, lat: 50.9866, type: "partner", name: "imec", city: "Leuven, Flemish Brabant, Belgium", region: "EMEA", source: "IBM Semiconductor" },
    { id: "partner-kyndryl", lon: -73.9782, lat: 40.7527, type: "partner", name: "Kyndryl", city: "New York, New York, United States", region: "Americas", source: "IBM Spinoff" },
    { id: "client-verizon", lon: -74.4915, lat: 40.7056, type: "client", name: "Verizon", city: "Basking Ridge, New Jersey, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-fedex", lon: -90.0518, lat: 35.1526, type: "client", name: "FedEx", city: "Memphis, Tennessee, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-home-depot", lon: -84.4881, lat: 33.8704, type: "client", name: "The Home Depot", city: "Atlanta, Georgia, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-bmw", lon: 11.559, lat: 48.1771, type: "client", name: "BMW Group", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Case Study" },
    { id: "client-bank-of-america", lon: -80.8431, lat: 35.2271, type: "client", name: "Bank of America", city: "Charlotte, North Carolina, United States", region: "Americas", source: "IBM Case Study" },
    { id: "client-walmart", lon: -94.2218, lat: 36.3659, type: "client", name: "Walmart", city: "Bentonville, Arkansas, United States", region: "Americas", source: "IBM Case Study" },
    { id: "initiative-quantum-poughkeepsie", lon: -73.9317, lat: 41.6501, type: "initiative", name: "IBM Quantum Data Center", city: "Poughkeepsie, New York, United States", region: "Americas", source: "IBM Quantum" },
    { id: "initiative-quantum-ehningen", lon: 8.9416, lat: 48.6575, type: "initiative", name: "IBM Quantum Data Center", city: "Ehningen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Quantum" },
    { id: "initiative-quantum-melbourne", lon: 144.9614, lat: -37.7963, type: "initiative", name: "IBM Quantum Innovation Center", city: "Melbourne, Victoria, Australia", region: "APAC", source: "IBM Quantum" },
    { id: "initiative-quantum-madras", lon: 80.2339, lat: 12.9915, type: "initiative", name: "IBM Quantum Innovation Center", city: "Chennai, Tamil Nadu, India", region: "APAC", source: "IBM Quantum" },
    { id: "initiative-quantum-ncstate", lon: -78.6744, lat: 35.7872, type: "initiative", name: "IBM Quantum Innovation Center", city: "Raleigh, North Carolina, United States", region: "Americas", source: "IBM Quantum" },

];


const REGIONS = ["Americas", "EMEA", "APAC"];

const IBM_ACTIVITIES = [
    { type: "office", name: "Gatineau CIC", location: "Quebec, Canada", metric: "Cloud hub", value: "Active" },
    { type: "client", name: "JPMorgan Chase", location: "New York", metric: "Contract", value: "Renewed" },
    { type: "partner", name: "Confluent", location: "Mountain View", metric: "Acquired", value: "2026" },
    { type: "initiative", name: "Anderon Foundry", location: "Albany, NY", metric: "CHIPS", value: "$2B" },
];

const IBM_STATS = {
    offices: "169",
    countries: "170+",
    sites: "222",
    cloudRegions: 34,
    labs: 12,
    employees: "~288K",
    enterpriseClients: "12.4K",
    consulting: "3.2K",
    dependencies: 33,
    quantum: 9,
    sustainability: 67,
    revenue: "$62.8B",
    growth: "14.2",
    patents: "150K+",
};
