/** IBM WRLD — offices, clients, dependencies, initiatives */

const SITE_TYPES = {
    office: {
        label: "Office",
        color: "#0f62fe",
        markerCore: "#b8d4ff",
        markerGlow: "rgba(140, 185, 255, 0.5)",
        abbr: "O",
    },
    client: {
        label: "Client",
        color: "#ee5396",
        markerCore: "#f4b8d4",
        markerGlow: "rgba(240, 160, 200, 0.45)",
        abbr: "C",
    },
    partner: {
        label: "Dependency",
        color: "#ff832b",
        markerCore: "#ffd4a8",
        markerGlow: "rgba(255, 190, 120, 0.45)",
        abbr: "D",
    },
    initiative: {
        label: "Initiative",
        color: "#8a3ffc",
        markerCore: "#d4c4ff",
        markerGlow: "rgba(180, 150, 255, 0.45)",
        abbr: "I",
    },
};

const IBM_SITES = [
    { lon: -73.7246, lat: 41.1084, type: "office", name: "Armonk Headquarters", city: "Armonk, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -97.7202, lat: 30.4042, type: "office", name: "IBM Austin", city: "Austin, Texas, United States", region: "Americas", source: "IBM Locations" },
    { lon: -121.8041, lat: 37.2081, type: "office", name: "IBM Silicon Valley Lab", city: "San Jose, California, United States", region: "Americas", source: "IBM Silicon Valley" },
    { lon: -78.8559, lat: 35.9132, type: "office", name: "IBM Research Triangle Park", city: "Durham, North Carolina, United States", region: "Americas", source: "IBM Locations" },
    { lon: -71.0825, lat: 42.3628, type: "office", name: "IBM Cambridge", city: "Cambridge, Massachusetts, United States", region: "Americas", source: "IBM Research" },
    { lon: -73.9317, lat: 41.6501, type: "office", name: "IBM Poughkeepsie", city: "Poughkeepsie, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -96.7970, lat: 32.7767, type: "office", name: "IBM Dallas", city: "Dallas, Texas, United States", region: "Americas", source: "IBM Cloud" },
    { lon: -87.6219, lat: 41.8885, type: "office", name: "IBM Chicago", city: "Chicago, Illinois, United States", region: "Americas", source: "IBM Locations" },
    { lon: -84.4578, lat: 33.8961, type: "office", name: "IBM Atlanta", city: "Atlanta, Georgia, United States", region: "Americas", source: "IBM Locations" },
    { lon: -79.3341, lat: 43.8471, type: "office", name: "IBM Toronto Software Lab", city: "Markham, Ontario, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -73.5693, lat: 45.4984, type: "office", name: "IBM Montreal", city: "Montreal, Quebec, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -99.2559, lat: 19.3663, type: "office", name: "IBM Mexico", city: "Mexico City, CDMX, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -103.2678, lat: 20.5372, type: "office", name: "IBM Guadalajara", city: "El Salto, Jalisco, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -46.6433, lat: -23.5855, type: "office", name: "IBM São Paulo", city: "São Paulo, São Paulo, Brazil", region: "Americas", source: "IBM Brazil" },
    { lon: -58.3739, lat: -34.5937, type: "office", name: "IBM Argentina", city: "Buenos Aires, CABA, Argentina", region: "Americas", source: "IBM Argentina" },
    { lon: -74.0436, lat: 4.6853, type: "office", name: "IBM Colombia", city: "Bogotá, Bogotá, Colombia", region: "Americas", source: "IBM Colombia" },
    { lon: -0.1147, lat: 51.5036, type: "office", name: "IBM London", city: "London, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -1.3965, lat: 51.0264, type: "office", name: "IBM Hursley", city: "Winchester, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -6.4172, lat: 53.4116, type: "office", name: "IBM Dublin", city: "Dublin, County Dublin, Ireland", region: "EMEA", source: "IBM Ireland" },
    { lon: 2.2688, lat: 48.9189, type: "office", name: "IBM France HQ", city: "Bois-Colombes, Île-de-France, France", region: "EMEA", source: "IBM France" },
    { lon: -3.6685, lat: 40.4507, type: "office", name: "IBM Spain", city: "Madrid, Madrid, Spain", region: "EMEA", source: "IBM Spain" },
    { lon: 12.4332, lat: 41.8152, type: "office", name: "IBM Italy", city: "Rome, Lazio, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 9.3005, lat: 45.4808, type: "office", name: "IBM Milan", city: "Segrate, Lombardy, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 8.5521, lat: 47.3092, type: "office", name: "IBM Research Zurich", city: "Rüschlikon, Zurich, Switzerland", region: "EMEA", source: "IBM Research" },
    { lon: 8.9792, lat: 48.6756, type: "office", name: "IBM Germany R&D", city: "Böblingen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 11.5925, lat: 48.1755, type: "office", name: "IBM Munich", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 8.5721, lat: 50.1346, type: "office", name: "IBM Frankfurt", city: "Frankfurt, Hesse, Germany", region: "EMEA", source: "IBM Cloud" },
    { lon: 4.8276, lat: 52.3421, type: "office", name: "IBM Netherlands", city: "Amsterdam, North Holland, Netherlands", region: "EMEA", source: "IBM Netherlands" },
    { lon: 14.3971, lat: 50.1504, type: "office", name: "IBM Czech Republic", city: "Prague, Prague, Czechia", region: "EMEA", source: "IBM CZ" },
    { lon: 19.8974, lat: 50.0827, type: "office", name: "IBM Poland", city: "Kraków, Lesser Poland, Poland", region: "EMEA", source: "IBM Poland" },
    { lon: 34.8085, lat: 32.0699, type: "office", name: "IBM Israel", city: "Givatayim, Tel Aviv, Israel", region: "EMEA", source: "IBM Israel" },
    { lon: 55.1633, lat: 25.0994, type: "office", name: "IBM UAE", city: "Dubai, Dubai, UAE", region: "EMEA", source: "IBM Middle East" },
    { lon: 28.0494, lat: -26.1035, type: "office", name: "IBM South Africa", city: "Sandton, Gauteng, South Africa", region: "EMEA", source: "IBM South Africa" },
    { lon: 77.5946, lat: 12.9716, type: "office", name: "IBM Bangalore", city: "Bangalore, Karnataka, India", region: "APAC", source: "IBM India" },
    { lon: 73.9806, lat: 18.5793, type: "office", name: "IBM Pune", city: "Pune, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 78.3756, lat: 17.4474, type: "office", name: "IBM Hyderabad", city: "Hyderabad, Telangana, India", region: "APAC", source: "IBM India" },
    { lon: 80.2281, lat: 12.8953, type: "office", name: "IBM Chennai", city: "Chennai, Tamil Nadu, India", region: "APAC", source: "IBM India" },
    { lon: 72.8596, lat: 19.1025, type: "office", name: "IBM Mumbai", city: "Mumbai, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 139.7871, lat: 35.6791, type: "office", name: "IBM Japan HQ", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 135.5023, lat: 34.6937, type: "office", name: "IBM Osaka", city: "Osaka, Osaka, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 116.2796, lat: 40.0464, type: "office", name: "IBM Research China", city: "Beijing, Beijing, China", region: "APAC", source: "IBM China" },
    { lon: 121.3994, lat: 31.2117, type: "office", name: "IBM Shanghai", city: "Shanghai, Shanghai, China", region: "APAC", source: "IBM China" },
    { lon: 126.9247, lat: 37.5256, type: "office", name: "IBM Korea", city: "Seoul, Seoul, South Korea", region: "APAC", source: "IBM Korea" },
    { lon: 121.5645, lat: 25.0345, type: "office", name: "IBM Taiwan", city: "Taipei, Taipei, Taiwan", region: "APAC", source: "IBM Taiwan" },
    { lon: 103.9632, lat: 1.3341, type: "office", name: "IBM Singapore", city: "Singapore, Singapore, Singapore", region: "APAC", source: "IBM Singapore" },
    { lon: 101.6146, lat: 3.1368, type: "office", name: "IBM Malaysia", city: "Kuala Lumpur, Federal Territory, Malaysia", region: "APAC", source: "IBM Malaysia" },
    { lon: 121.0543, lat: 14.6214, type: "office", name: "IBM Philippines", city: "Quezon City, Metro Manila, Philippines", region: "APAC", source: "IBM Philippines" },
    { lon: 151.1963, lat: -33.8214, type: "office", name: "IBM Sydney", city: "St Leonards, New South Wales, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 144.9626, lat: -37.8229, type: "office", name: "IBM Melbourne", city: "Southbank, Victoria, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 174.7633, lat: -36.8485, type: "office", name: "IBM New Zealand", city: "Auckland, Auckland, New Zealand", region: "APAC", source: "IBM New Zealand" },
    { lon: -73.81, lat: 41.03, type: "initiative", name: "IBM Research Yorktown", city: "New York, USA", region: "Americas" },
    { lon: -95.99, lat: 41.26, type: "initiative", name: "IBM Quantum — Omaha", city: "Nebraska, USA", region: "Americas" },
    { lon: 11.58, lat: 48.14, type: "initiative", name: "Quantum — Munich", city: "Germany", region: "EMEA" },
    { lon: 116.40, lat: 39.90, type: "client", name: "Beijing Financial District", city: "China", region: "APAC" },
    { lon: -87.63, lat: 41.88, type: "client", name: "Chicago Enterprise Hub", city: "USA", region: "Americas" },
    { lon: 4.90, lat: 52.37, type: "client", name: "Amsterdam Client Center", city: "Netherlands", region: "EMEA" },
    { lon: 55.27, lat: 25.20, type: "client", name: "Dubai", city: "UAE", region: "EMEA" },
    { lon: -99.13, lat: 19.43, type: "client", name: "Mexico City", city: "Mexico", region: "Americas" },
    { lon: 18.42, lat: -33.92, type: "client", name: "Cape Town", city: "South Africa", region: "EMEA" },
    { lon: -122.42, lat: 37.77, type: "partner", name: "Red Hat — San Francisco", city: "USA", region: "Americas" },
    { lon: -77.04, lat: 38.91, type: "partner", name: "HashiCorp — Washington DC", city: "USA", region: "Americas" },
    { lon: 13.40, lat: 52.52, type: "partner", name: "SAP Alliance — Berlin", city: "Germany", region: "EMEA" },
    { lon: 100.50, lat: 13.75, type: "partner", name: "AWS Interconnect — Bangkok", city: "Thailand", region: "APAC" },
    { lon: 126.98, lat: 37.57, type: "partner", name: "Samsung Foundry — Seoul", city: "South Korea", region: "APAC" },
    { lon: -0.10, lat: 51.52, type: "partner", name: "Vodafone — London", city: "UK", region: "EMEA" },
    { lon: 144.96, lat: -37.81, type: "initiative", name: "Sustainability — Melbourne", city: "Australia", region: "APAC" },
    { lon: -43.17, lat: -22.91, type: "initiative", name: "Green Data Center — Rio", city: "Brazil", region: "Americas" },
];

const REGIONS = ["Americas", "EMEA", "APAC"];

const IBM_ACTIVITIES = [
    { icon: "O", type: "office", name: "Watson IoT — Munich", location: "Germany", metric: "Opened", value: "2025" },
    { icon: "C", type: "client", name: "JPMorgan Chase", location: "New York", metric: "Contract", value: "Renewed" },
    { icon: "D", type: "partner", name: "Microsoft Azure", location: "Global", metric: "Integration", value: "Active" },
    { icon: "I", type: "initiative", name: "watsonx.ai rollout", location: "APAC", metric: "Phase", value: "3/5" },
];

const IBM_STATS = {
    offices: "49",
    countries: "170+",
    sites: "420+",
    cloudRegions: 34,
    labs: 12,
    employees: "~288K",
    enterpriseClients: "12.4K",
    consulting: "3.2K",
    dependencies: 840,
    quantum: 5,
    sustainability: 67,
    revenue: "$62.8B",
    growth: "14.2",
    patents: "150K+",
};
