/** IBM WRLD — offices, clients, dependencies, initiatives */

const SITE_TYPES = {
    office: {
        label: "Office",
        color: "#0f62fe",
        markerCore: "#b8d4ff",
        markerGlow: "rgba(140, 185, 255, 0.5)",
        abbr: "O",
    },
    client: {
        label: "Client",
        color: "#ee5396",
        markerCore: "#f4b8d4",
        markerGlow: "rgba(240, 160, 200, 0.45)",
        abbr: "C",
    },
    partner: {
        label: "Dependency",
        color: "#ff832b",
        markerCore: "#ffd4a8",
        markerGlow: "rgba(255, 190, 120, 0.45)",
        abbr: "D",
    },
    initiative: {
        label: "Initiative",
        color: "#8a3ffc",
        markerCore: "#d4c4ff",
        markerGlow: "rgba(180, 150, 255, 0.45)",
        abbr: "I",
    },
};

const IBM_SITES = [
    { lon: -73.7246, lat: 41.1084, type: "office", name: "Armonk Headquarters", city: "Armonk, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -97.7202, lat: 30.4042, type: "office", name: "IBM Austin", city: "Austin, Texas, United States", region: "Americas", source: "IBM Locations" },
    { lon: -121.8041, lat: 37.2081, type: "office", name: "IBM Silicon Valley Lab", city: "San Jose, California, United States", region: "Americas", source: "IBM Silicon Valley" },
    { lon: -78.8559, lat: 35.9132, type: "office", name: "IBM Research Triangle Park", city: "Durham, North Carolina, United States", region: "Americas", source: "IBM Locations" },
    { lon: -71.0825, lat: 42.3628, type: "office", name: "IBM Cambridge", city: "Cambridge, Massachusetts, United States", region: "Americas", source: "IBM Research" },
    { lon: -73.9317, lat: 41.6501, type: "office", name: "IBM Poughkeepsie", city: "Poughkeepsie, New York, United States", region: "Americas", source: "IBM Locations" },
    { lon: -96.7970, lat: 32.7767, type: "office", name: "IBM Dallas", city: "Dallas, Texas, United States", region: "Americas", source: "IBM Cloud" },
    { lon: -87.6219, lat: 41.8885, type: "office", name: "IBM Chicago", city: "Chicago, Illinois, United States", region: "Americas", source: "IBM Locations" },
    { lon: -84.4578, lat: 33.8961, type: "office", name: "IBM Atlanta", city: "Atlanta, Georgia, United States", region: "Americas", source: "IBM Locations" },
    { lon: -79.3341, lat: 43.8471, type: "office", name: "IBM Toronto Software Lab", city: "Markham, Ontario, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -73.5693, lat: 45.4984, type: "office", name: "IBM Montreal", city: "Montreal, Quebec, Canada", region: "Americas", source: "IBM Canada" },
    { lon: -99.2559, lat: 19.3663, type: "office", name: "IBM Mexico", city: "Mexico City, CDMX, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -103.2678, lat: 20.5372, type: "office", name: "IBM Guadalajara", city: "El Salto, Jalisco, Mexico", region: "Americas", source: "IBM Mexico" },
    { lon: -46.6433, lat: -23.5855, type: "office", name: "IBM São Paulo", city: "São Paulo, São Paulo, Brazil", region: "Americas", source: "IBM Brazil" },
    { lon: -58.3739, lat: -34.5937, type: "office", name: "IBM Argentina", city: "Buenos Aires, CABA, Argentina", region: "Americas", source: "IBM Argentina" },
    { lon: -74.0436, lat: 4.6853, type: "office", name: "IBM Colombia", city: "Bogotá, Bogotá, Colombia", region: "Americas", source: "IBM Colombia" },
    { lon: -0.1147, lat: 51.5036, type: "office", name: "IBM London", city: "London, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -1.3965, lat: 51.0264, type: "office", name: "IBM Hursley", city: "Winchester, England, United Kingdom", region: "EMEA", source: "IBM UK" },
    { lon: -6.4172, lat: 53.4116, type: "office", name: "IBM Dublin", city: "Dublin, County Dublin, Ireland", region: "EMEA", source: "IBM Ireland" },
    { lon: 2.2688, lat: 48.9189, type: "office", name: "IBM France HQ", city: "Bois-Colombes, Île-de-France, France", region: "EMEA", source: "IBM France" },
    { lon: -3.6685, lat: 40.4507, type: "office", name: "IBM Spain", city: "Madrid, Madrid, Spain", region: "EMEA", source: "IBM Spain" },
    { lon: 12.4332, lat: 41.8152, type: "office", name: "IBM Italy", city: "Rome, Lazio, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 9.3005, lat: 45.4808, type: "office", name: "IBM Milan", city: "Segrate, Lombardy, Italy", region: "EMEA", source: "IBM Italy" },
    { lon: 8.5521, lat: 47.3092, type: "office", name: "IBM Research Zurich", city: "Rüschlikon, Zurich, Switzerland", region: "EMEA", source: "IBM Research" },
    { lon: 8.9792, lat: 48.6756, type: "office", name: "IBM Germany R&D", city: "Böblingen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 11.5925, lat: 48.1755, type: "office", name: "IBM Munich", city: "Munich, Bavaria, Germany", region: "EMEA", source: "IBM Germany" },
    { lon: 8.5721, lat: 50.1346, type: "office", name: "IBM Frankfurt", city: "Frankfurt, Hesse, Germany", region: "EMEA", source: "IBM Cloud" },
    { lon: 4.8276, lat: 52.3421, type: "office", name: "IBM Netherlands", city: "Amsterdam, North Holland, Netherlands", region: "EMEA", source: "IBM Netherlands" },
    { lon: 14.3971, lat: 50.1504, type: "office", name: "IBM Czech Republic", city: "Prague, Prague, Czechia", region: "EMEA", source: "IBM CZ" },
    { lon: 19.8974, lat: 50.0827, type: "office", name: "IBM Poland", city: "Kraków, Lesser Poland, Poland", region: "EMEA", source: "IBM Poland" },
    { lon: 34.8085, lat: 32.0699, type: "office", name: "IBM Israel", city: "Givatayim, Tel Aviv, Israel", region: "EMEA", source: "IBM Israel" },
    { lon: 55.1633, lat: 25.0994, type: "office", name: "IBM UAE", city: "Dubai, Dubai, UAE", region: "EMEA", source: "IBM Middle East" },
    { lon: 28.0494, lat: -26.1035, type: "office", name: "IBM South Africa", city: "Sandton, Gauteng, South Africa", region: "EMEA", source: "IBM South Africa" },
    { lon: 77.5946, lat: 12.9716, type: "office", name: "IBM Bangalore", city: "Bangalore, Karnataka, India", region: "APAC", source: "IBM India" },
    { lon: 73.9806, lat: 18.5793, type: "office", name: "IBM Pune", city: "Pune, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 78.3756, lat: 17.4474, type: "office", name: "IBM Hyderabad", city: "Hyderabad, Telangana, India", region: "APAC", source: "IBM India" },
    { lon: 80.2281, lat: 12.8953, type: "office", name: "IBM Chennai", city: "Chennai, Tamil Nadu, India", region: "APAC", source: "IBM India" },
    { lon: 72.8596, lat: 19.1025, type: "office", name: "IBM Mumbai", city: "Mumbai, Maharashtra, India", region: "APAC", source: "IBM India" },
    { lon: 139.7871, lat: 35.6791, type: "office", name: "IBM Japan HQ", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 135.5023, lat: 34.6937, type: "office", name: "IBM Osaka", city: "Osaka, Osaka, Japan", region: "APAC", source: "IBM Japan" },
    { lon: 116.2796, lat: 40.0464, type: "office", name: "IBM Research China", city: "Beijing, Beijing, China", region: "APAC", source: "IBM China" },
    { lon: 121.3994, lat: 31.2117, type: "office", name: "IBM Shanghai", city: "Shanghai, Shanghai, China", region: "APAC", source: "IBM China" },
    { lon: 126.9247, lat: 37.5256, type: "office", name: "IBM Korea", city: "Seoul, Seoul, South Korea", region: "APAC", source: "IBM Korea" },
    { lon: 121.5645, lat: 25.0345, type: "office", name: "IBM Taiwan", city: "Taipei, Taipei, Taiwan", region: "APAC", source: "IBM Taiwan" },
    { lon: 103.9632, lat: 1.3341, type: "office", name: "IBM Singapore", city: "Singapore, Singapore, Singapore", region: "APAC", source: "IBM Singapore" },
    { lon: 101.6146, lat: 3.1368, type: "office", name: "IBM Malaysia", city: "Kuala Lumpur, Federal Territory, Malaysia", region: "APAC", source: "IBM Malaysia" },
    { lon: 121.0543, lat: 14.6214, type: "office", name: "IBM Philippines", city: "Quezon City, Metro Manila, Philippines", region: "APAC", source: "IBM Philippines" },
    { lon: 151.1963, lat: -33.8214, type: "office", name: "IBM Sydney", city: "St Leonards, New South Wales, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 144.9626, lat: -37.8229, type: "office", name: "IBM Melbourne", city: "Southbank, Victoria, Australia", region: "APAC", source: "IBM Australia" },
    { lon: 174.7633, lat: -36.8485, type: "office", name: "IBM New Zealand", city: "Auckland, Auckland, New Zealand", region: "APAC", source: "IBM New Zealand" },
    { id: "ibm-kochi-wtc", lon: 76.3630, lat: 10.0150, type: "office", name: "IBM Kochi WTC", city: "Kochi, Kerala, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-noida", lon: 77.4055, lat: 28.5042, type: "office", name: "IBM Noida", city: "Noida, Uttar Pradesh, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-ahmedabad", lon: 72.5714, lat: 23.0225, type: "office", name: "IBM Ahmedabad", city: "Ahmedabad, Gujarat, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-hong-kong", lon: 114.1717, lat: 22.2796, type: "office", name: "IBM Hong Kong", city: "Hong Kong, Hong Kong, China", region: "APAC", source: "IBM HK" },
    { id: "ibm-shenzhen", lon: 113.9377, lat: 22.5431, type: "office", name: "IBM Shenzhen", city: "Shenzhen, Guangdong, China", region: "APAC", source: "IBM China", subtype: "delivery_center" },
    { id: "ibm-dalian", lon: 121.5330, lat: 38.8680, type: "office", name: "IBM Dalian", city: "Dalian, Liaoning, China", region: "APAC", source: "IBM China", subtype: "delivery_center" },
    { id: "ibm-jakarta", lon: 106.8043, lat: -6.2238, type: "office", name: "IBM Indonesia", city: "Jakarta, Jakarta, Indonesia", region: "APAC", source: "IBM Indonesia" },
    { id: "ibm-bangkok", lon: 100.5428, lat: 13.7801, type: "office", name: "IBM Thailand", city: "Bangkok, Bangkok, Thailand", region: "APAC", source: "IBM Thailand" },
    { id: "ibm-brisbane", lon: 153.0251, lat: -27.4698, type: "office", name: "IBM Brisbane", city: "Brisbane, Queensland, Australia", region: "APAC", source: "IBM Australia" },
    { id: "ibm-wellington", lon: 174.7797, lat: -41.2822, type: "office", name: "IBM Wellington", city: "Wellington, Wellington, New Zealand", region: "APAC", source: "IBM NZ" },
    { id: "ibm-ehningen-hq", lon: 8.9416, lat: 48.6575, type: "office", name: "IBM Germany HQ", city: "Ehningen, Baden-Württemberg, Germany", region: "EMEA", source: "IBM Germany", subtype: "hq" },
    { id: "ibm-montpellier", lon: 3.8741, lat: 43.6146, type: "office", name: "IBM Montpellier", city: "Montpellier, Occitanie, France", region: "EMEA", source: "IBM France", subtype: "client_center" },
    { id: "ibm-brno", lon: 16.5960, lat: 49.2140, type: "office", name: "IBM Brno", city: "Brno, South Moravian, Czechia", region: "EMEA", source: "IBM CZ", subtype: "delivery_center" },
    { id: "ibm-budapest", lon: 19.0594, lat: 47.4734, type: "office", name: "IBM Hungary", city: "Budapest, Budapest, Hungary", region: "EMEA", source: "IBM Hungary", subtype: "delivery_center" },
    { id: "ibm-warsaw", lon: 20.9859, lat: 52.2309, type: "office", name: "IBM Poland HQ", city: "Warsaw, Masovian, Poland", region: "EMEA", source: "IBM Poland", subtype: "hq" },
    { id: "ibm-bucharest", lon: 26.1030, lat: 44.4429, type: "office", name: "IBM Romania", city: "Bucharest, Bucharest, Romania", region: "EMEA", source: "IBM Romania", subtype: "delivery_center" },
    { id: "ibm-stockholm", lon: 17.9547, lat: 59.4045, type: "office", name: "IBM Sweden", city: "Stockholm, Stockholm, Sweden", region: "EMEA", source: "IBM Sweden", subtype: "hq" },
    { id: "ibm-copenhagen", lon: 12.5768, lat: 55.6375, type: "office", name: "IBM Denmark", city: "Copenhagen, Capital Region, Denmark", region: "EMEA", source: "IBM Denmark", subtype: "hq" },
    { id: "ibm-riyadh", lon: 46.7020, lat: 24.7296, type: "office", name: "IBM Saudi Arabia", city: "Riyadh, Riyadh, Saudi Arabia", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-cairo", lon: 31.2089, lat: 30.0131, type: "office", name: "IBM Egypt", city: "Cairo, Cairo, Egypt", region: "EMEA", source: "IBM Egypt", subtype: "delivery_center" },
    { id: "ibm-casablanca", lon: -7.6038, lat: 33.5898, type: "office", name: "IBM Morocco", city: "Casablanca, Casablanca-Settat, Morocco", region: "EMEA", source: "IBM Morocco" },
    { id: "ibm-nyc-astor", lon: -73.9904, lat: 40.7303, type: "office", name: "IBM New York City", city: "New York, New York, United States", region: "Americas", source: "IBM Locations", subtype: "client_center" },
    { id: "ibm-rochester", lon: -92.5029, lat: 44.0535, type: "office", name: "IBM Rochester", city: "Rochester, Minnesota, United States", region: "Americas", source: "IBM Locations", subtype: "lab" },
    { id: "ibm-washington-dc", lon: -77.0315, lat: 38.9011, type: "office", name: "IBM Washington DC", city: "Washington, DC, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-costa-mesa", lon: -117.8828, lat: 33.6826, type: "office", name: "IBM Costa Mesa", city: "Costa Mesa, California, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-ottawa", lon: -75.7483, lat: 45.3400, type: "office", name: "IBM Ottawa", city: "Ottawa, Ontario, Canada", region: "Americas", source: "IBM Canada" },
    { id: "ibm-hortolandia", lon: -47.2023, lat: -22.8687, type: "office", name: "IBM Hortolândia", city: "Hortolândia, São Paulo, Brazil", region: "Americas", source: "IBM Brazil", subtype: "delivery_center" },
    { id: "ibm-santiago", lon: -70.6133, lat: -33.4243, type: "office", name: "IBM Chile", city: "Santiago, Santiago Metropolitan, Chile", region: "Americas", source: "IBM Chile" },
    { id: "ibm-costa-rica", lon: -84.1198, lat: 9.9980, type: "office", name: "IBM Costa Rica", city: "Heredia, Heredia, Costa Rica", region: "Americas", source: "IBM Costa Rica", subtype: "delivery_center" },
    { id: "ibm-lima", lon: -77.0252, lat: -12.0963, type: "office", name: "IBM Peru", city: "Lima, Lima, Peru", region: "Americas", source: "IBM Peru" },
    { id: "ibm-yorktown-research", lon: -73.8016, lat: 41.2104, type: "office", name: "IBM Thomas J. Watson Research Center", city: "Yorktown Heights, New York, United States", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-almaden-research", lon: -121.8080, lat: 37.2105, type: "office", name: "IBM Research Almaden", city: "San Jose, California, United States", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-boulder", lon: -105.2014, lat: 40.0632, type: "office", name: "IBM Boulder", city: "Boulder, Colorado, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-southbury", lon: -73.2201, lat: 41.4886, type: "office", name: "IBM Southbury", city: "Southbury, Connecticut, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-bromont", lon: -72.6713, lat: 45.3025, type: "office", name: "IBM Bromont", city: "Bromont, Quebec, Canada", region: "Americas", source: "IBM Canada", subtype: "manufacturing" },
    { id: "ibm-rio-research", lon: -43.1750, lat: -22.9519, type: "office", name: "IBM Research Brazil", city: "Rio de Janeiro, Rio de Janeiro, Brazil", region: "Americas", source: "IBM Research", subtype: "research" },
    { id: "ibm-nairobi-research", lon: 36.7578, lat: -1.2581, type: "office", name: "IBM Research Africa", city: "Nairobi, Nairobi, Kenya", region: "EMEA", source: "IBM Research", subtype: "research" },
    { id: "ibm-haifa-research", lon: 34.9950, lat: 32.7601, type: "office", name: "IBM Research Haifa", city: "Haifa, Haifa, Israel", region: "EMEA", source: "IBM Research", subtype: "research" },
    { id: "ibm-vienna", lon: 16.3773, lat: 48.2255, type: "office", name: "IBM Austria", city: "Vienna, Vienna, Austria", region: "EMEA", source: "IBM Austria" },
    { id: "ibm-brussels", lon: 4.3644, lat: 50.8548, type: "office", name: "IBM Belgium", city: "Brussels, Brussels, Belgium", region: "EMEA", source: "IBM Belgium" },
    { id: "ibm-helsinki", lon: 24.8778, lat: 60.2227, type: "office", name: "IBM Finland", city: "Helsinki, Uusimaa, Finland", region: "EMEA", source: "IBM Finland" },
    { id: "ibm-oslo", lon: 10.7605, lat: 59.9142, type: "office", name: "IBM Norway", city: "Oslo, Oslo, Norway", region: "EMEA", source: "IBM Norway" },
    { id: "ibm-lisbon", lon: -9.1388, lat: 38.7369, type: "office", name: "IBM Portugal", city: "Lisbon, Lisbon, Portugal", region: "EMEA", source: "IBM Portugal" },
    { id: "ibm-athens", lon: 23.8055, lat: 38.0264, type: "office", name: "IBM Greece", city: "Athens, Attica, Greece", region: "EMEA", source: "IBM Greece" },
    { id: "ibm-istanbul", lon: 29.0145, lat: 41.0847, type: "office", name: "IBM Turkey", city: "Istanbul, Istanbul, Turkey", region: "EMEA", source: "IBM Turkey" },
    { id: "ibm-cyberjaya", lon: 101.6569, lat: 2.9221, type: "office", name: "IBM Cyberjaya", city: "Cyberjaya, Selangor, Malaysia", region: "APAC", source: "IBM Malaysia", subtype: "delivery_center" },
    { id: "ibm-ho-chi-minh", lon: 106.7009, lat: 10.7769, type: "office", name: "IBM Vietnam", city: "Ho Chi Minh City, HCMC, Vietnam", region: "APAC", source: "IBM Vietnam" },
    { id: "ibm-perth", lon: 115.8605, lat: -31.9505, type: "office", name: "IBM Perth", city: "Perth, Western Australia, Australia", region: "APAC", source: "IBM Australia" },
    { id: "ibm-colombo", lon: 79.8612, lat: 6.9271, type: "office", name: "IBM Sri Lanka", city: "Colombo, Western Province, Sri Lanka", region: "APAC", source: "IBM Sri Lanka" },
    { id: "ibm-coimbatore", lon: 76.9558, lat: 11.0168, type: "office", name: "IBM Coimbatore", city: "Coimbatore, Tamil Nadu, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-gurugram", lon: 77.0266, lat: 28.4595, type: "office", name: "IBM Gurugram", city: "Gurugram, Haryana, India", region: "APAC", source: "IBM India" },
    { id: "ibm-kolkata", lon: 88.4716, lat: 22.5867, type: "office", name: "IBM Kolkata", city: "Kolkata, West Bengal, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-bhubaneswar", lon: 85.8245, lat: 20.2961, type: "office", name: "IBM Bhubaneswar", city: "Bhubaneswar, Odisha, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-canberra", lon: 149.1300, lat: -35.2809, type: "office", name: "IBM Canberra", city: "Canberra, Australian Capital Territory, Australia", region: "APAC", source: "IBM Australia" },
    { id: "ibm-adelaide", lon: 138.6007, lat: -34.9285, type: "office", name: "IBM Adelaide", city: "Adelaide, South Australia, Australia", region: "APAC", source: "IBM Australia", subtype: "client_center" },
    { id: "ibm-yamato-lab", lon: 139.4124, lat: 35.6186, type: "office", name: "IBM Yamato Facility", city: "Tokyo, Tokyo, Japan", region: "APAC", source: "IBM Japan", subtype: "lab" },
    { id: "ibm-nagoya", lon: 136.9066, lat: 35.1814, type: "office", name: "IBM Nagoya", city: "Nagoya, Aichi, Japan", region: "APAC", source: "IBM Japan" },
    { id: "ibm-manila-eastwood", lon: 121.0801, lat: 14.6092, type: "office", name: "IBM Manila Eastwood", city: "Quezon City, Metro Manila, Philippines", region: "APAC", source: "IBM Philippines", subtype: "delivery_center" },
    { id: "ibm-bratislava", lon: 17.1077, lat: 48.1486, type: "office", name: "IBM Bratislava", city: "Bratislava, Bratislava Region, Slovakia", region: "EMEA", source: "IBM Slovakia", subtype: "delivery_center" },
    { id: "ibm-manchester", lon: -2.2426, lat: 53.4808, type: "office", name: "IBM Manchester", city: "Manchester, Greater Manchester, United Kingdom", region: "EMEA", source: "IBM UK" },
    { id: "ibm-edinburgh", lon: -3.1883, lat: 55.9533, type: "office", name: "IBM Edinburgh", city: "Edinburgh, Scotland, United Kingdom", region: "EMEA", source: "IBM UK" },
    { id: "ibm-barcelona", lon: 2.1734, lat: 41.3851, type: "office", name: "IBM Barcelona", city: "Barcelona, Catalonia, Spain", region: "EMEA", source: "IBM Spain", subtype: "client_center" },
    { id: "ibm-lyon", lon: 4.8357, lat: 45.7640, type: "office", name: "IBM Lyon", city: "Lyon, Auvergne-Rhône-Alpes, France", region: "EMEA", source: "IBM France" },
    { id: "ibm-sofia", lon: 23.3219, lat: 42.6977, type: "office", name: "IBM Bulgaria", city: "Sofia, Sofia City, Bulgaria", region: "EMEA", source: "IBM Bulgaria", subtype: "delivery_center" },
    { id: "ibm-abu-dhabi", lon: 54.3773, lat: 24.4539, type: "office", name: "IBM Abu Dhabi", city: "Abu Dhabi, Abu Dhabi, UAE", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-doha", lon: 51.5310, lat: 25.2854, type: "office", name: "IBM Qatar", city: "Doha, Doha, Qatar", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-lagos", lon: 3.4219, lat: 6.4281, type: "office", name: "IBM Nigeria", city: "Lagos, Lagos State, Nigeria", region: "EMEA", source: "IBM Africa" },
    { id: "ibm-calgary", lon: -114.0719, lat: 51.0447, type: "office", name: "IBM Calgary", city: "Calgary, Alberta, Canada", region: "Americas", source: "IBM Canada", subtype: "client_center" },
    { id: "ibm-vancouver", lon: -123.1207, lat: 49.2827, type: "office", name: "IBM Vancouver", city: "Vancouver, British Columbia, Canada", region: "Americas", source: "IBM Canada" },
    { id: "ibm-pittsburgh", lon: -79.9959, lat: 40.4406, type: "office", name: "IBM Pittsburgh", city: "Pittsburgh, Pennsylvania, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-columbus", lon: -83.0125, lat: 40.0336, type: "office", name: "IBM Columbus", city: "Columbus, Ohio, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-denver", lon: -104.9125, lat: 39.6172, type: "office", name: "IBM Denver", city: "Greenwood Village, Colorado, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-phoenix", lon: -112.0740, lat: 33.4484, type: "office", name: "IBM Phoenix", city: "Phoenix, Arizona, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-monterrey", lon: -100.3161, lat: 25.6866, type: "office", name: "IBM Monterrey", city: "Monterrey, Nuevo León, Mexico", region: "Americas", source: "IBM Mexico" },
    { id: "ibm-brasilia", lon: -47.8822, lat: -15.7942, type: "office", name: "IBM Brasília", city: "Brasília, Federal District, Brazil", region: "Americas", source: "IBM Brazil" },
    { id: "ibm-medellin", lon: -75.5812, lat: 6.2442, type: "office", name: "IBM Medellín", city: "Medellín, Antioquia, Colombia", region: "Americas", source: "IBM Colombia", subtype: "delivery_center" },
    { id: "ibm-warwick", lon: -1.5842, lat: 52.2801, type: "office", name: "IBM Warwick", city: "Warwick, Warwickshire, United Kingdom", region: "EMEA", source: "IBM UK", subtype: "campus" },
    { id: "ibm-cork", lon: -8.4756, lat: 51.8985, type: "office", name: "IBM Cork", city: "Cork, Munster, Ireland", region: "EMEA", source: "IBM Ireland" },
    { id: "ibm-littleton", lon: -71.4801, lat: 42.5401, type: "office", name: "IBM Littleton Lab", city: "Littleton, Massachusetts, United States", region: "Americas", source: "IBM Locations", subtype: "lab" },
    { id: "ibm-groningen", lon: 6.5665, lat: 53.2194, type: "office", name: "IBM Groningen CIC", city: "Groningen, Groningen, Netherlands", region: "EMEA", source: "IBM Netherlands", subtype: "client_center" },
    { id: "ibm-wroclaw", lon: 17.0385, lat: 51.1079, type: "office", name: "IBM Wrocław", city: "Wrocław, Lower Silesian, Poland", region: "EMEA", source: "IBM Poland", subtype: "delivery_center" },
    { id: "ibm-katowice", lon: 19.0238, lat: 50.2649, type: "office", name: "IBM Katowice", city: "Katowice, Silesian, Poland", region: "EMEA", source: "IBM Poland", subtype: "delivery_center" },
    { id: "ibm-berlin", lon: 13.4050, lat: 52.5200, type: "office", name: "IBM Berlin", city: "Berlin, Berlin, Germany", region: "EMEA", source: "IBM Germany" },
    { id: "ibm-hamburg", lon: 9.9937, lat: 53.5511, type: "office", name: "IBM Hamburg", city: "Hamburg, Hamburg, Germany", region: "EMEA", source: "IBM Germany" },
    { id: "ibm-mysuru", lon: 76.6394, lat: 12.2958, type: "office", name: "IBM Mysuru", city: "Mysuru, Karnataka, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-gandhinagar", lon: 72.6369, lat: 23.2156, type: "office", name: "IBM Gandhinagar", city: "Gandhinagar, Gujarat, India", region: "APAC", source: "IBM India" },
    { id: "ibm-nagpur", lon: 79.0882, lat: 21.1458, type: "office", name: "IBM Nagpur", city: "Nagpur, Maharashtra, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-vizag", lon: 83.2185, lat: 17.6868, type: "office", name: "IBM Visakhapatnam", city: "Visakhapatnam, Andhra Pradesh, India", region: "APAC", source: "IBM India", subtype: "delivery_center" },
    { id: "ibm-guangzhou", lon: 113.2644, lat: 23.1291, type: "office", name: "IBM Guangzhou", city: "Guangzhou, Guangdong, China", region: "APAC", source: "IBM China" },
    { id: "ibm-chengdu", lon: 104.0648, lat: 30.6586, type: "office", name: "IBM Chengdu", city: "Chengdu, Sichuan, China", region: "APAC", source: "IBM China" },
    { id: "ibm-wuhan", lon: 114.3055, lat: 30.5928, type: "office", name: "IBM Wuhan", city: "Wuhan, Hubei, China", region: "APAC", source: "IBM China" },
    { id: "ibm-hanoi", lon: 105.8542, lat: 21.0285, type: "office", name: "IBM Hanoi", city: "Hanoi, Hanoi, Vietnam", region: "APAC", source: "IBM Vietnam" },
    { id: "ibm-fukuoka", lon: 130.4017, lat: 33.5902, type: "office", name: "IBM Fukuoka", city: "Fukuoka, Fukuoka, Japan", region: "APAC", source: "IBM Japan" },
    { id: "ibm-houston", lon: -95.3698, lat: 29.7604, type: "office", name: "IBM Houston", city: "Houston, Texas, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-miami", lon: -80.2599, lat: 25.7505, type: "office", name: "IBM Miami", city: "Coral Gables, Florida, United States", region: "Americas", source: "IBM Locations" },
    { id: "ibm-ashburn", lon: -77.4875, lat: 39.0438, type: "office", name: "IBM Ashburn Data Center", city: "Ashburn, Virginia, United States", region: "Americas", source: "IBM Cloud", subtype: "cloud_region" },
    { id: "ibm-northcastle", lon: -73.7120, lat: 41.1140, type: "office", name: "IBM North Castle", city: "Armonk, New York, United States", region: "Americas", source: "IBM Locations", subtype: "campus" },
    { id: "ibm-queretaro", lon: -100.3899, lat: 20.5888, type: "office", name: "IBM Querétaro", city: "Querétaro, Querétaro, Mexico", region: "Americas", source: "IBM Cloud", subtype: "cloud_region" },
    { id: "ibm-jeddah", lon: 39.1728, lat: 21.5433, type: "office", name: "IBM Jeddah", city: "Jeddah, Makkah, Saudi Arabia", region: "EMEA", source: "IBM Middle East" },
    { id: "ibm-capetown", lon: 18.4241, lat: -33.9249, type: "office", name: "IBM Cape Town", city: "Cape Town, Western Cape, South Africa", region: "EMEA", source: "IBM South Africa" },
    { id: "ibm-accra", lon: -0.1870, lat: 5.6037, type: "office", name: "IBM Ghana", city: "Accra, Greater Accra, Ghana", region: "EMEA", source: "IBM Africa" },
    { lon: -73.81, lat: 41.03, type: "initiative", name: "IBM Research Yorktown", city: "New York, USA", region: "Americas" },
    { lon: -95.99, lat: 41.26, type: "initiative", name: "IBM Quantum — Omaha", city: "Nebraska, USA", region: "Americas" },
    { lon: 11.58, lat: 48.14, type: "initiative", name: "Quantum — Munich", city: "Germany", region: "EMEA" },
    { lon: 116.40, lat: 39.90, type: "client", name: "Beijing Financial District", city: "China", region: "APAC" },
    { lon: -87.63, lat: 41.88, type: "client", name: "Chicago Enterprise Hub", city: "USA", region: "Americas" },
    { lon: 4.90, lat: 52.37, type: "client", name: "Amsterdam Client Center", city: "Netherlands", region: "EMEA" },
    { lon: 55.27, lat: 25.20, type: "client", name: "Dubai", city: "UAE", region: "EMEA" },
    { lon: -99.13, lat: 19.43, type: "client", name: "Mexico City", city: "Mexico", region: "Americas" },
    { lon: 18.42, lat: -33.92, type: "client", name: "Cape Town", city: "South Africa", region: "EMEA" },
    { lon: -122.42, lat: 37.77, type: "partner", name: "Red Hat — San Francisco", city: "USA", region: "Americas" },
    { lon: -77.04, lat: 38.91, type: "partner", name: "HashiCorp — Washington DC", city: "USA", region: "Americas" },
    { lon: 13.40, lat: 52.52, type: "partner", name: "SAP Alliance — Berlin", city: "Germany", region: "EMEA" },
    { lon: 100.50, lat: 13.75, type: "partner", name: "AWS Interconnect — Bangkok", city: "Thailand", region: "APAC" },
    { lon: 126.98, lat: 37.57, type: "partner", name: "Samsung Foundry — Seoul", city: "South Korea", region: "APAC" },
    { lon: -0.10, lat: 51.52, type: "partner", name: "Vodafone — London", city: "UK", region: "EMEA" },
    { lon: 144.96, lat: -37.81, type: "initiative", name: "Sustainability — Melbourne", city: "Australia", region: "APAC" },
    { lon: -43.17, lat: -22.91, type: "initiative", name: "Green Data Center — Rio", city: "Brazil", region: "Americas" },
];

const REGIONS = ["Americas", "EMEA", "APAC"];

const IBM_ACTIVITIES = [
    { icon: "O", type: "office", name: "Watson IoT — Munich", location: "Germany", metric: "Opened", value: "2025" },
    { icon: "C", type: "client", name: "JPMorgan Chase", location: "New York", metric: "Contract", value: "Renewed" },
    { icon: "D", type: "partner", name: "Microsoft Azure", location: "Global", metric: "Integration", value: "Active" },
    { icon: "I", type: "initiative", name: "watsonx.ai rollout", location: "APAC", metric: "Phase", value: "3/5" },
];

const IBM_STATS = {
    offices: "151",
    countries: "170+",
    sites: "168",
    cloudRegions: 34,
    labs: 12,
    employees: "~288K",
    enterpriseClients: "12.4K",
    consulting: "3.2K",
    dependencies: 840,
    quantum: 5,
    sustainability: 67,
    revenue: "$62.8B",
    growth: "14.2",
    patents: "150K+",
};
